// blueprint.mjs — the blueprint-to-metal compiler core.
// Schema in (GraphQL-SDL subset), byte-exact fixed-offset layouts + monotonic
// join operators out. No runtime. Receipts always.
//
// Doctrine (the verdict on the 已落地 proposal, codified):
//   - join(max)  : semilattice-safe (idempotent, commutative, associative)
//   - join(xor)  : FINGERPRINT CLASS ONLY — an order-statistics-destroying flag,
//                  never a content merge. Labeled as such in every emitter.
//   - join(lww)  : last-writer-wins, tie-broken by an Int @primary field
//   - String     : varlen, lives OUTSIDE the fixed block (offset table only)
//   - no emitter may emit inline-asm "crypto". Wyhash-class hashes are labeled
//     fasthash/fingerprint, never "cryptographic".

export function fnv1a64(str) {
  let h = 0xcbf29ce484222325n;
  for (let i = 0; i < str.length; i++) {
    h ^= BigInt(str.charCodeAt(i));
    h = (h * 0x100000001b3n) & 0xffffffffffffffffn;
  }
  return h.toString(16).padStart(16, "0");
}

const SCALARS = { Int: "u64", Float: "f32", Boolean: "u8", ID: "u64" };
const JOIN_OK = new Set(["max", "xor", "lww"]);

export function parseSDL(src) {
  const types = [];
  const typeRe = /type\s+(\w+)\s*\{([^}]*)\}/gs;
  let m;
  while ((m = typeRe.exec(src))) {
    const fields = m[2].split("\n").map(l => l.trim()).filter(Boolean)
      .map(line => {
        const fm = line.match(/^(\w+)\s*:\s*([\w\[\]!]+)\s*(.*)$/);
        if (!fm) return null;
        const [, name, rawType, annots] = fm;
        const joinM = annots.match(/@join\((\w+)\)/);
        const join = joinM ? joinM[1] : null;
        if (join && !JOIN_OK.has(join)) throw new Error(`unknown @join(${join}) on ${name}`);
        return {
          name,
          type: rawType.replace(/[[\]!]/g, ""),
          join,
          primary: /@primary/.test(annots),
          packed: /@packed/.test(annots),
        };
      }).filter(Boolean);
    types.push({ name: m[1], fields });
  }
  return types;
}

const ALIGN = { i64: 8, u64: 8, f32: 4, u8: 1, u32: 4 };
const SIZEOF = { i64: 8, u64: 8, f32: 4, u8: 1, u32: 4 };

export function layout(type) {
  const fields = [];
  let offset = 0, maxAlign = 1;
  for (const f of type.fields) {
    if (f.type === "String") {
      fields.push({ ...f, ctype: "varlen", offset: -1, size: 0, varlen: true });
      continue;
    }
    const ctype = SCALARS[f.type] || "u32";
    const align = f.packed ? 1 : (ALIGN[ctype] || 1);
    if (!f.packed) offset = Math.ceil(offset / align) * align;
    maxAlign = Math.max(maxAlign, align);
    fields.push({ ...f, ctype, offset, size: SIZEOF[ctype] || 4, varlen: false });
    offset += SIZEOF[ctype] || 4;
  }
  if (!type.fields.some(f => f.packed)) offset = Math.ceil(offset / maxAlign) * maxAlign;
  return {
    name: type.name, size: offset, fields,
    axioms: ["idempotence", "commutativity", "associativity"],
    ceiling: "top — join of any two states is representable; convergence terminates",
  };
}

function zigJoin(f, primaryName) {
  if (f.join === "max") return `.${f.name} = @max(a.${f.name}, b.${f.name})`;
  if (f.join === "xor") return `.${f.name} = a.${f.name} ^ b.${f.name} // fingerprint class: order statistics destroyed; flag, not content`;
  if (f.join === "lww") return `.${f.name} = if (a.${primaryName} >= b.${primaryName}) a.${f.name} else b.${f.name}`;
  return `.${f.name} = a.${f.name} // not join-annotated: inherited from a; document or annotate`;
}

export function emit(type, lang) {
  const L = layout(type);
  const zt = { i64: "i64", u64: "u64", f32: "f32", u8: "u8", u32: "u32" };
  if (lang === "json") return JSON.stringify(L, null, 2);
  if (lang === "zig") {
    const body = L.fields.filter(f => !f.varlen)
      .map(f => `    ${f.name}: ${zt[f.ctype] || "u32"},`).join("\n");
    const joins = L.fields.filter(f => f.join)
      .map(f => `            ${zigJoin(f, L.fields.find(x => x.primary)?.name || "seq")},`).join("\n");
    return `// generated by quilt-blueprint — receipt ${receipt(type, "zig")}
// join axioms: idempotence, commutativity, associativity (semilattice)
pub const ${type.name} = struct {
${body}

    /// Pure join (⊔). Monotonic inflation; convergence terminates at ceiling.
    pub fn join(a: ${type.name}, b: ${type.name}) ${type.name} {
        return .{
${joins}
        };
    }

    /// fasthash integrity check — receipt-grade only; NOT a security boundary.
    pub fn fingerprintFast(self: *const ${type.name}) u64 {
        return std.hash.Wyhash.hash(0, std.mem.asBytes(self));
    }
};
`;
  }
  if (lang === "c") {
    const ct = { i64: "int64_t", u64: "uint64_t", f32: "float", u8: "uint8_t", u32: "uint32_t" };
    const body = L.fields.filter(f => !f.varlen)
      .map(f => `    ${ct[f.ctype] || "uint32_t"} ${f.name}; /* offset ${f.offset}, ${f.size}B ${f.join ? "join=" + f.join : ""} */`).join("\n");
    return `/* generated by quilt-blueprint — receipt ${receipt(type, "c")} */
#pragma pack(push, 1)
typedef struct ${type.name} {
${body}
} ${type.name};
#pragma pack(pop)
`;
  }
  throw new Error(`unknown lang ${lang}`);
}

export function receipt(type, lang) {
  // receipt over the CANONICAL json layout, so emitters agree with each other
  return fnv1a64(JSON.stringify(layout(type)));
}
